# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d58e2eaa0ab0db4313283b5fd46811d3727e854945424c1598b34147c3ff205ea92844aedd143f130674fdc7d129c76fc5e6495369c3e3e4a6c3c0f7245604cf
  jwt_secret: 'super random key'
  jwt_expiration_hours: 24

test:
  secret_key_base: 7e1b5e5d32910cc54e9a9d15499627db94de1c5c9e018999f9de92c7a1bf7084b26b90fbbe6613e53d4d15138750e6f1aa20d6d6ccfdf24407df73b4089b7f14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jwt_secret: 'even more super random key'
  jwt_expiration_hours: 6
